#############################################################################
# Makefile for building: hddtest
# Generated by qmake (2.01a) (Qt 4.8.5) on: Tue Jul 22 12:08:11 2014
# Project:  hddtest.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile hddtest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DBUS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtDBus -L/usr/lib64 -L/usr/lib64/qt4 -lQtXml -lQtGui -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		hddtest.cpp \
		randomgenerator.cpp \
		seeker.cpp \
		readrnd.cpp \
		device.cpp \
		readcont.cpp \
		readblock.cpp \
		filerw.cpp \
		filestructure.cpp \
		smallfiles.cpp \
		testwidget.cpp \
		definitions.cpp \
		file.cpp \
		timer.cpp \
		testthread.cpp \
		udisksinterface.cpp \
		udisksdeviceinterface.cpp \
		about.cpp moc_hddtest.cpp \
		moc_device.cpp \
		moc_testwidget.cpp \
		moc_file.cpp \
		moc_testthread.cpp \
		moc_udisksinterface.cpp \
		moc_udisksdeviceinterface.cpp \
		moc_about.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		hddtest.o \
		randomgenerator.o \
		seeker.o \
		readrnd.o \
		device.o \
		readcont.o \
		readblock.o \
		filerw.o \
		filestructure.o \
		smallfiles.o \
		testwidget.o \
		definitions.o \
		file.o \
		timer.o \
		testthread.o \
		udisksinterface.o \
		udisksdeviceinterface.o \
		about.o \
		moc_hddtest.o \
		moc_device.o \
		moc_testwidget.o \
		moc_file.o \
		moc_testthread.o \
		moc_udisksinterface.o \
		moc_udisksdeviceinterface.o \
		moc_about.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hddtest.pro
QMAKE_TARGET  = hddtest
DESTDIR       = 
TARGET        = hddtest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_hddtest.h ui_testwidget.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: hddtest.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtDBus.prl \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile hddtest.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtDBus.prl:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile hddtest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hddtest1.0.0 || $(MKDIR) .tmp/hddtest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hddtest1.0.0/ && $(COPY_FILE) --parents hddtest.h randomgenerator.h seeker.h readrnd.h device.h readcont.h readblock.h filerw.h filestructure.h filestructure.h smallfiles.h testwidget.h definitions.h file.h timer.h testthread.h udisksinterface.h udisksdeviceinterface.h about.h .tmp/hddtest1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/hddtest1.0.0/ && $(COPY_FILE) --parents main.cpp hddtest.cpp randomgenerator.cpp seeker.cpp readrnd.cpp device.cpp readcont.cpp readblock.cpp filerw.cpp filestructure.cpp smallfiles.cpp testwidget.cpp definitions.cpp file.cpp timer.cpp testthread.cpp udisksinterface.cpp udisksdeviceinterface.cpp about.cpp .tmp/hddtest1.0.0/ && $(COPY_FILE) --parents hddtest.ui testwidget.ui about.ui .tmp/hddtest1.0.0/ && (cd `dirname .tmp/hddtest1.0.0` && $(TAR) hddtest1.0.0.tar hddtest1.0.0 && $(COMPRESS) hddtest1.0.0.tar) && $(MOVE) `dirname .tmp/hddtest1.0.0`/hddtest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hddtest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_hddtest.cpp moc_device.cpp moc_testwidget.cpp moc_file.cpp moc_testthread.cpp moc_udisksinterface.cpp moc_udisksdeviceinterface.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_hddtest.cpp moc_device.cpp moc_testwidget.cpp moc_file.cpp moc_testthread.cpp moc_udisksinterface.cpp moc_udisksdeviceinterface.cpp moc_about.cpp
moc_hddtest.cpp: about.h \
		seeker.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		readrnd.h \
		readcont.h \
		readblock.h \
		filerw.h \
		file.h \
		filestructure.h \
		smallfiles.h \
		hddtest.h
	/usr/bin/moc $(DEFINES) $(INCPATH) hddtest.h -o moc_hddtest.cpp

moc_device.cpp: definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		device.h
	/usr/bin/moc $(DEFINES) $(INCPATH) device.h -o moc_device.cpp

moc_testwidget.cpp: device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		testwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) testwidget.h -o moc_testwidget.cpp

moc_file.cpp: definitions.h \
		timer.h \
		device.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		file.h
	/usr/bin/moc $(DEFINES) $(INCPATH) file.h -o moc_file.cpp

moc_testthread.cpp: testthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) testthread.h -o moc_testthread.cpp

moc_udisksinterface.cpp: udisksinterface.h
	/usr/bin/moc $(DEFINES) $(INCPATH) udisksinterface.h -o moc_udisksinterface.cpp

moc_udisksdeviceinterface.cpp: udisksdeviceinterface.h
	/usr/bin/moc $(DEFINES) $(INCPATH) udisksdeviceinterface.h -o moc_udisksdeviceinterface.cpp

moc_about.cpp: about.h
	/usr/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		icon/help-about.png \
		icon/process-stop.png \
		icon/document-open.png \
		icon/hdd.svg \
		icon/document-save.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_hddtest.h ui_testwidget.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_hddtest.h ui_testwidget.h ui_about.h
ui_hddtest.h: hddtest.ui \
		seeker.h \
		readrnd.h \
		filerw.h \
		readcont.h \
		readblock.h \
		filestructure.h \
		smallfiles.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		definitions.h \
		testwidget.h \
		device.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		file.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		testwidget.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	/usr/bin/uic hddtest.ui -o ui_hddtest.h

ui_testwidget.h: testwidget.ui
	/usr/bin/uic testwidget.ui -o ui_testwidget.h

ui_about.h: about.ui
	/usr/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp hddtest.h \
		about.h \
		seeker.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		readrnd.h \
		readcont.h \
		readblock.h \
		filerw.h \
		file.h \
		filestructure.h \
		smallfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

hddtest.o: hddtest.cpp hddtest.h \
		about.h \
		seeker.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h \
		readrnd.h \
		readcont.h \
		readblock.h \
		filerw.h \
		file.h \
		filestructure.h \
		smallfiles.h \
		ui_hddtest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hddtest.o hddtest.cpp

randomgenerator.o: randomgenerator.cpp randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o randomgenerator.o randomgenerator.cpp

seeker.o: seeker.cpp seeker.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seeker.o seeker.cpp

readrnd.o: readrnd.cpp readrnd.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readrnd.o readrnd.cpp

device.o: device.cpp device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o device.o device.cpp

readcont.o: readcont.cpp readcont.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		testwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readcont.o readcont.cpp

readblock.o: readblock.cpp readblock.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readblock.o readblock.cpp

filerw.o: filerw.cpp filerw.h \
		definitions.h \
		testwidget.h \
		device.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filerw.o filerw.cpp

filestructure.o: filestructure.cpp filestructure.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filestructure.o filestructure.cpp

smallfiles.o: smallfiles.cpp smallfiles.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smallfiles.o smallfiles.cpp

testwidget.o: testwidget.cpp testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h \
		ui_testwidget.h \
		testthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testwidget.o testwidget.cpp

definitions.o: definitions.cpp definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o definitions.o definitions.cpp

file.o: file.cpp file.h \
		definitions.h \
		timer.h \
		device.h \
		udisksinterface.h \
		udisksdeviceinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

timer.o: timer.cpp timer.h \
		definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timer.o timer.cpp

testthread.o: testthread.cpp testthread.h \
		testwidget.h \
		device.h \
		definitions.h \
		timer.h \
		udisksinterface.h \
		udisksdeviceinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testthread.o testthread.cpp

udisksinterface.o: udisksinterface.cpp udisksinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udisksinterface.o udisksinterface.cpp

udisksdeviceinterface.o: udisksdeviceinterface.cpp udisksdeviceinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udisksdeviceinterface.o udisksdeviceinterface.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_hddtest.o: moc_hddtest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hddtest.o moc_hddtest.cpp

moc_device.o: moc_device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_device.o moc_device.cpp

moc_testwidget.o: moc_testwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testwidget.o moc_testwidget.cpp

moc_file.o: moc_file.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_file.o moc_file.cpp

moc_testthread.o: moc_testthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testthread.o moc_testthread.cpp

moc_udisksinterface.o: moc_udisksinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udisksinterface.o moc_udisksinterface.cpp

moc_udisksdeviceinterface.o: moc_udisksdeviceinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udisksdeviceinterface.o moc_udisksdeviceinterface.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/bin/ || $(MKDIR) $(INSTALL_ROOT)/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

