/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c UDisksDeviceInterface -p ./udisksdeviceinterface.h:./udisksdeviceinterface.cpp org.freedesktop.UDisks.Device.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "./udisksdeviceinterface.h"

/*
 * Implementation of interface class UDisksDeviceInterface
 */

UDisksDeviceInterface::UDisksDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

UDisksDeviceInterface::~UDisksDeviceInterface()
{
}
